### ISSUE TITLE
d1bg1a1 (4-helix bundles)

### ISSUE THREAD

**Issue by lafita** [rcsb/symmetry-benchmark#32]
Examples like this one should be tagged as some sort of symmetry. Although they are 4 helices, it would be interesting to determine if they are arranged in some sort of symmetry (they share a common transformation operation). In this case C2 makes sense, and maybe C4 or D2 could be also possible.

**Comment by lafita** [comment]
For example, to be consistent: why do we tag this one d1or6b_ as C2? They look the same

**Comment by sbliven** [comment]
It's an issue of the helix direction. d1bg1a1 does not have any 2-fold axes that preserve the helix direction. You could argue for open symmetry (helices 1+2 onto 3+4), but I've always found 4-helix bundles uninteresting and favored low-symmetry.

You can also find decent order-independent alignments for bundles with this topology, but then you lose connectivity. For instance, 1+3 onto 2+4 (axis perpendicular to the bundle) or 1+2 onto 4+3. You can even find some degree of mirror symmetry, to whatever extent mirror symmetry can be meaningful in a protein.

**Comment by sbliven** [comment]
Overall, we are fairly inconsistent with helical bundles. For instance, I would annotated d2okua1 as C1, but for some reason that I've now forgotten, the other team members all advocated C2.

**Comment by sbliven** [comment]
Even the 'classic' 4-helix bundle topology (e.g. d2j9wa_) doesn't make too much sense as a C2. Why not go all the way to D2? Intuitively I don't believe the symmetry is significant in any way, but if the structure aligns with reasonable RMSD I'm unable to find a criteria that separates them from other alignments that I would consider relevant.

**Comment by lafita** [comment]
After reviewing the helical cases I would say that this one is H2 with 4 repeats, because although there are only 4 helices they are repeated in a helical pattern.

**Comment by lafita** [comment]
d1bg1a1 has also H2 connectivity. It should be moved to H2 and 4 repeats.

**Comment by sbliven** [comment]
Superseded by #58
