### ISSUE TITLE
d1af0a1 partially helical

### ISSUE THREAD

**Issue by lafita** [rcsb/symmetry-benchmark#39]
The dommain has N and C terminal regions that do not participate in the helix, but the internal beta strand H2 helix is clear and up to 12 beta strands can be identified to participate.

**Comment by sbliven** [comment]
Topology (counting "strands" as anything aligned with the sheet, even through two lack proper strand-like h-bonds):

```
1     3 7  9 11 13 17 16 15
2 6 5 4 8 10 12 14 18
```

Is the H2/12 that you mentioned composed of 3-4,7-14,17-18? One could also argue for just the core 7-14.

**Comment by sbliven** [comment]
Lets do H2/10 composed of 3-4,7-14. The last two strands are getting a bit too divergent (18 isn't even a strand technically)

**Comment by lafita** [comment]
I agree. Because the symmetry group is unambiguous here, when evaluating order detection algorithms on the benchmark a penalty that depends on the actual-predicted order can be implemented (in that case both order 8, conservative, and order 12 will score high).
