### ISSUE TITLE
d1kx9a_ asymmetric

### ISSUE THREAD

**Issue by lafita** [rcsb/symmetry-benchmark#43]
This domain is a helical bundle. It has two repeats, but with very low coverage overall. It is certainly not H3, as annotated.

**Comment by lafita** [comment]
CE aligns one long helix with two perpendicular helices.

**Comment by sbliven** [comment]
Yes, R/2 seems borderline (align helices 1+2 with 4+5, leave 3 and 6 unaligned). I would support either C1 or R/2, but definitely not H3.

**Comment by lafita** [comment]
I think C1 makes more sense to be consistent with our criteria on coverage.
