### ISSUE TITLE
d1v0fd2 asymmetric

### ISSUE THREAD

**Issue by lafita** [rcsb/symmetry-benchmark#44]
An overall helix can be weakly visualized, but it is interrupted in the middle and the whole domain look quite unstructured (without repetitive SSE). I would annotate this as C1.

**Comment by lafita** [comment]
The structure is C3 symmetric and the three chains complement each other into a helix-like structure, but at the quaternary level. There is no internal symmetry.

**Comment by lafita** [comment]
SCOP: each chain donates 3 beta-strands per turn of the helix.

**Comment by sbliven** [comment]
Also the length of each strand is quite different for each turn. I agree this should be C1, although I understand why it was originally assigned as helical.
