### ISSUE TITLE
4 Helical Bundles review

### ISSUE THREAD

**Issue by lafita** [rcsb/symmetry-benchmark#58]
4 helical bundles are not consistently annotated in the benchmark.
The criteria is as follows:
- The coverage of the 4 helices has to be at least half of the length of the structure.
- The 4 helices have to be of similar length and orientation.
- The connectivity determines the symmetry assigned:
    - zig zag connectivity gets assigned H2 and 4 repeats.
    - parallel connectivity gets assigned D2 symmetry.

<pre>
Zig-zag (crossed) connectivity:
                                  12
                                  34

Parallel connectivity:
                                  12
                                  43
</pre>

**Comment by sbliven** [comment]
We inspected all benchmark members of folds annotated as 4-helical bundles (a.24, a.26, and f.21), as well as some additional folds identified manually as potentially having 4-helix bundles (a.29, a.47, a.48, a.60, and f.36).

An initial assignment was made based on topology:
```
D2:   H2:
1-2   1-2
  |    /
4-3   3-4
```
Cases that significantly diverged from four parallel helices underwent further consideration. Reasons for diverging from the standard D2/H2 assignments are given as comments.


Domain | SCOP | Call | Comments
---|---|---|---
d1ea8a_ | a.24.1.1  |   D2 |
d1rmva_ | a.24.5.1  |   C1 |not enough coverage by bundle
d1hy5a_ | a.24.11.1 |   C1 |too kinked
d2ga0e_ | a.24.12.0 |   D2 |
d1wola_ | a.24.16.0 |   C1 |not parallel
d1v74b_ | a.24.20.1 |   D2 |
d3g50b_ | a.24.22.1 |   D2 |
d1ug7a_ | a.24.24.1 |   D2 |
d2ap3a1 | a.24.27.1 |   D2 |
d2j9wa_ | a.24.28.0 |   D2 |
d2p61a1 | a.24.29.1 |   D2 |but poor angles
d1x91a_ | a.29.6.1  |   D2 |
d1v9va1 | a.29.10.1 |   D2 |
d2fefc1 | a.29.11.1 |   D2 |
d3dbyh2 | a.29.13.1 |   D2 |
d2gscb_ | a.29.16.1 |   D2 |
d1bg1a1 | a.47.1.1  |   H2 |
d1s2xa_ | a.47.3.1  |   C1 |fourth helix too kinked to align
d3pmra_ | a.47.4.0  |   C1 |wildly different lengths
d1t98a2 | a.47.6.1  |   C1 |N-term is too short, inconsistent orientation
d1a0pa1 | a.60.9.1  |   C2 |secondary axis is off-center, helix lengths match in C2
d3ezea1 | a.60.10.1 |   C2 |off-center
d1ryka_ | a.60.11.1 |   C1 |not parallel
d3ci0k1 | a.60.16.1 |   C1 |too short for a bundle
d1y5ic1 | f.21.3.1  |   C1 |not 4-helix, despite description
d1oedd_ | f.36.1.1  |   D2 |

**Comment by sbliven** [comment]
This issue supersedes  #51 #52 #53 #54 #55 #56 #57
