### ISSUE TITLE
CA-only structures

### ISSUE THREAD

**Issue by sbliven** [rcsb/symmetry-benchmark#66]
Five domains from the benchmark have only C-alpha atoms:

domain | description | symmetry | possible replacements
------- | ----------- | --- | ---
d1i95b_ | ribosome S2 | C1 | d2uubb1 or 4Y4O.1b
d1i96v_ | IF3 | C2 | 5LMN.X:83-169 (poor fit)
d2rdo81 | Ribosome recycling factor | C1 | d1isea_ (hinge movement)
d2rdow1 | Ribosome L27 | C1 | d2gycu1 (obsoleted for 4V4W.U)
d3b5zd2 | MsbA | C1 | d3b60d2

All of the structures have a 100%id all-atom replacement. In several cases the replacement differs structurally from the low-res version, as expected.

Should we replace the 5 benchmark items?

**Comment by lafita** [comment]
Yes sounds good! Although we only use CA it is better to have good quality and complete structures in benchmarks.

**Comment by lafita** [comment]
All the replacement options for `d1i96v_` are EM structures. What should we do about this? 

I vote for removing this entry as first option or leaving the X-ray structure (even if it is CA only as second option).

**Comment by sbliven** [comment]
Let's keep the old structures as the official benchmark, but allow these replacements if the software can't handle CA-only.
